CONSOLE_ENABLE = no
LCD_BACKLIGHT_ENABLE = yes
LCD_ENABLE = yes
BACKLIGHT_ENABLE = no
FORCE_NKRO = no
NKRO_ENABLE = yes
KEY_LOCK_ENABLE = no
MOUSEKEY_ENABLE = yes
VISUALIZER_ENABLE = yes
TAP_DANCE_ENABLE = no

